[package]
name = "twitterDMsCLI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18"
crossterm = "0.23"
egg-mode = "0.16"
futures = "0.3.21"